//-------------------------------------------------------------------------------------------------
// <auto-generated> 
// Marked as auto-generated so StyleCop will ignore BDD style tests
// </auto-generated>
//-------------------------------------------------------------------------------------------------

#pragma warning disable 169
// ReSharper disable InconsistentNaming
// ReSharper disable UnusedMember.Global
// ReSharper disable UnusedMember.Local

namespace Redbadger.Web.ScriptDependencyResolver.Specs
{
    using Machine.Specifications;

    using RedBadger.Web.ScriptDependencyResolver.Extensions;

    [Subject(typeof(StringExtensions), "AppendPath")]
    public class when_an_app_relative_path_is_appended_to_a_reference_path
    {
        private const string Path = "~/path";

        private const string Root = @"d:\dir";

        private static string actual;

        private Because of = () => actual = Root.AppendPath(Path);

        private It should_produce_the_correct_path = () => actual.ShouldEqual(@"d:\dir\path");
    }
}